INSERT INTO USERROLE
SELECT * FROM (SELECT 1,'admin role', 'ROLE_ADMIN') AS tmp
WHERE NOT EXISTS (
    SELECT id FROM USERROLE WHERE id = 1
) LIMIT 1;

INSERT INTO USERROLE
SELECT * FROM (SELECT 2,'default user role', 'ROLE_USER') AS tmp
WHERE NOT EXISTS (
    SELECT id FROM USERROLE WHERE id = 2
) LIMIT 1;


INSERT INTO USER(id, email, enabled, password)
SELECT * FROM (SELECT 1,'admin', true,'{bcrypt}$2a$10$eWPyYgZ7O6mWRLAS3nonleZe8jaLQOzRtABRLiUo7mtKT1/yS3Vhu') AS tmp
WHERE NOT EXISTS (
    SELECT id FROM USER WHERE id = 1
) LIMIT 1;

INSERT INTO USER_USERROLE
SELECT * FROM (SELECT 1,'1') AS tmp
WHERE NOT EXISTS (
    SELECT user_id FROM USER_USERROLE WHERE user_id = 1
) LIMIT 1;